# SHIELD Docker Compose Configuration

version: '3.8'

services:
  # SHIELD Backend API
  shield-backend:
    build: .
    container_name: shield-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY:-shield-production-key-change-me}
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shield-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: shield-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - shield-backend
    restart: unless-stopped
    networks:
      - shield-network

  # Redis for job queuing (Phase 2)
  redis:
    image: redis:7-alpine
    container_name: shield-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - shield-network
    profiles:
      - phase2

networks:
  shield-network:
    driver: bridge

volumes:
  redis-data: